BEGIN TRANSACTION;
DROP TABLE IF EXISTS `BALANCE`;
CREATE TABLE IF NOT EXISTS `BALANCE` (
	`ID`	INTEGER,
	`EXCHANGE`	INTEGER,
	`WALLET`	INTEGER,
	`CURRENCY`	DOUBLE NOT NULL DEFAULT 0,
	`BALANCE`	DOUBLE DEFAULT 0,
	FOREIGN KEY(`CURRENCY`) REFERENCES `CURRENCY`(`ID`) ON DELETE CASCADE,
	FOREIGN KEY(`WALLET`) REFERENCES `WALLET`(`ID`) ON DELETE CASCADE,
	PRIMARY KEY(`ID`),
	FOREIGN KEY(`EXCHANGE`) REFERENCES `EXCHANGE`(`ID`) ON DELETE CASCADE
);
INSERT INTO `BALANCE` VALUES (33,NULL,1,31.0,418.504333496094);
INSERT INTO `BALANCE` VALUES (34,NULL,1,27.0,2835.9921875);
INSERT INTO `BALANCE` VALUES (35,NULL,2,8.0,20.1573753356934);
COMMIT;
