BEGIN TRANSACTION;
DROP TABLE IF EXISTS `WALLET_TYPE`;
CREATE TABLE IF NOT EXISTS `WALLET_TYPE` (
	`ID`	INTEGER,
	`TYPE`	TEXT,
	PRIMARY KEY(`ID`)
);
DROP TABLE IF EXISTS `WALLET`;
CREATE TABLE IF NOT EXISTS `WALLET` (
	`ID`	INTEGER,
	`ADDRESS`	TEXT,
	`NAME`	TEXT,
	`WALLET_TYPE`	INTEGER NOT NULL,
	`ADDRESS_TYPE`	INTEGER NOT NULL,
	PRIMARY KEY(`ID`),
	FOREIGN KEY(`WALLET_TYPE`) REFERENCES `WALLET_TYPE`(`ID`) ON DELETE CASCADE,
	FOREIGN KEY(`ADDRESS_TYPE`) REFERENCES `ADDRESS_TYPE`(`ID`) ON DELETE CASCADE
);
DROP TABLE IF EXISTS `POSITION`;
CREATE TABLE IF NOT EXISTS `POSITION` (
	`ID`	TEXT,
	`CURRENCY`	DOUBLE NOT NULL,
	`AMOUNT`	DOUBLE DEFAULT 0,
	`COST`	DOUBLE DEFAULT 0,
	`PURCHASE_DATE`	TEXT,
	`PURCHASE_CURRENCY`	DOUBLE,
	`SIDE`	TEXT,
	`FIAT_COST`	DOUBLE,
	`EXCHANGE`	DOUBLE,
	FOREIGN KEY(`CURRENCY`) REFERENCES `CURRENCY`(`ID`) ON DELETE CASCADE,
	FOREIGN KEY(`PURCHASE_CURRENCY`) REFERENCES `CURRENCY`(`ID`) ON DELETE CASCADE,
	FOREIGN KEY(`EXCHANGE`) REFERENCES `EXCHANGE`(`ID`),
	PRIMARY KEY(`ID`)
);
DROP TABLE IF EXISTS `HISTORICAL_EXCHANGE_RATE`;
CREATE TABLE IF NOT EXISTS `HISTORICAL_EXCHANGE_RATE` (
	`id`	INTEGER,
	`close`	DOUBLE NOT NULL,
	`high`	DOUBLE NOT NULL,
	`low`	DOUBLE NOT NULL,
	`open`	DOUBLE NOT NULL,
	`time`	DOUBLE NOT NULL,
	`currency_pair`	DOUBLE NOT NULL,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`currency_pair`) REFERENCES `CURRENCY_PAIR`(`ID`) ON DELETE CASCADE,
	UNIQUE(`currency_pair`,`time`)
);
DROP TABLE IF EXISTS `EXCHANGE`;
CREATE TABLE IF NOT EXISTS `EXCHANGE` (
	`ID`	DOUBLE NOT NULL,
	`NAME`	DOUBLE NOT NULL DEFAULT 0,
	`API`	DOUBLE DEFAULT 0,
	PRIMARY KEY(`ID`),
	FOREIGN KEY(`ID`) REFERENCES `WALLET`(`ID`) ON DELETE CASCADE,
	FOREIGN KEY(`NAME`) REFERENCES `CURRENCY`(`ID`) ON DELETE CASCADE
);
DROP TABLE IF EXISTS `CURRENCY_TYPE`;
CREATE TABLE IF NOT EXISTS `CURRENCY_TYPE` (
	`ID`	INTEGER,
	`TYPE`	TEXT UNIQUE,
	PRIMARY KEY(`ID`)
);
DROP TABLE IF EXISTS `CURRENCY_PAIR`;
CREATE TABLE IF NOT EXISTS `CURRENCY_PAIR` (
	`ID`	INTEGER,
	`WATCH_LISTED`	TEXT,
	`BASE_CURRENCY`	INTEGER NOT NULL,
	`DENOMINATED_CURRENCY`	INTEGER NOT NULL,
	`SPOT_RATE`	TEXT,
	`7D_EXCHANGE_DELTA`	INTEGER,
	`1D_EXCHANGE_DELTA`	TEXT,
	FOREIGN KEY(`BASE_CURRENCY`) REFERENCES `CURRENCY`(`ID`) ON DELETE CASCADE,
	FOREIGN KEY(`DENOMINATED_CURRENCY`) REFERENCES `CURRENCY`(`ID`) ON DELETE CASCADE,
	PRIMARY KEY(`ID`),
	UNIQUE(`BASE_CURRENCY`,`DENOMINATED_CURRENCY`)
);
DROP TABLE IF EXISTS `CURRENCY`;
CREATE TABLE IF NOT EXISTS `CURRENCY` (
	`ID`	INTEGER,
	`NAME`	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	`CODE`	INTEGER NOT NULL UNIQUE COLLATE NOCASE,
	`TYPE`	INTEGER NOT NULL,
	`BALANCE_ENDPOINT`	TEXT,
	`BALANACE_RESPONSE_PATH`	TEXT,
	`BALANCE_DECIMAL_PLACE`	DOUBLE,
	`IS_EXCHANGE_CURRENCY`	INTEGER NOT NULL DEFAULT 0,
	`ADDRESS_TYPE`	INTEGER,
	FOREIGN KEY(`ADDRESS_TYPE`) REFERENCES `ADDRESS_TYPE`(`ID`),
	FOREIGN KEY(`TYPE`) REFERENCES `CURRENCY_TYPE`(`ID`) ON DELETE CASCADE,
	PRIMARY KEY(`ID`)
);
DROP TABLE IF EXISTS `BALANCE`;
CREATE TABLE IF NOT EXISTS `BALANCE` (
	`ID`	DOUBLE NOT NULL,
	`CURRENCY`	DOUBLE NOT NULL DEFAULT 0,
	`BALANCE`	DOUBLE DEFAULT 0,
	FOREIGN KEY(`ID`) REFERENCES `WALLET`(`ID`) ON DELETE CASCADE,
	FOREIGN KEY(`CURRENCY`) REFERENCES `CURRENCY`(`ID`) ON DELETE CASCADE,
	PRIMARY KEY(`ID`,`CURRENCY`)
);
DROP TABLE IF EXISTS `ADDRESS_TYPE`;
CREATE TABLE IF NOT EXISTS `ADDRESS_TYPE` (
	`ID`	INTEGER,
	`TYPE`	TEXT,
	PRIMARY KEY(`ID`)
);
COMMIT;
